# Generated by Django 5.2 on 2025-04-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='foreman.site'),
        ),
        migrations.AlterField(
            model_name='human_resource',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_resources', to='foreman.site'),
        ),
    ]
