# Generated by Django 5.2 on 2025-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0004_asset_owner_human_resource_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
