# Generated by Django 5.2 on 2025-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0005_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_resource',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
