# Generated by Django 5.2 on 2025-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0006_human_resource_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human_resource',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
