# Generated by Django 5.2 on 2025-09-10 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0008_alter_human_resource_phone_number_assettransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in_stock__gte', 0)), name='asset_qty_non_negative'),
        ),
    ]
