# Generated by Django 5.2 on 2025-09-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0009_asset_asset_qty_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='asset_qty_non_negative',
        ),
    ]
