# Generated by Django 5.2 on 2025-09-11 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0010_remove_asset_asset_qty_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in_stock__gte', 0)), name='asset_qty_non_negative'),
        ),
    ]
